### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by itzjakm** [adrian88888888/AHK_Virtual_Desktop_Library#1]
Why when i do this:
`#Include, AHK_Virtual_Desktop_Library.ahk
#!p::
activeHwnd := GetActiveHwnd() 
toggle = IsPinnedWindow(activeHwnd)
msgBox, %toggle%
If (%toggle% = 1) {
msgBox, Unpined
PinWindow(activeHwnd)
}
else If (%toggle% = 0) {
msgBox, Pined
UnPinWindow(activeHwnd)
}`
toggle sets to "IsPinnedWindow(activeHwnd)" and not 1 or 0?

**Comment by adrian88888888** [comment]
Please explain more, because i'm having a hard time understanding
If I understand right,(which i'm probably not) you have to do  "isPinned := IsPinnedWindow(activeHwnd)"  outside your toggle and it will work with no problem

**Comment by itzjakm** [comment]
If i put:
`#Include, AHK_Virtual_Desktop_Library.ahk
#!p::
activeHwnd := GetActiveHwnd() 
isPinned = IsPinnedWindow(activeHwnd)
msgBox, %isPinned%
If (isPinned = 1) {
msgBox, Unpined
PinWindow(activeHwnd)
}
else If (isPinned = 0) {
msgBox, Pined
UnPinWindow(activeHwnd)
}
`
It dosent pin the window, and in the "msgBox, %isPinned%" it gives a msg that says litteraly "IsPinnedWindow(activeHwnd)"

**Comment by adrian88888888** [comment]
Your code has a ton of misspells, that's why, these lines:
`isPinned = IsPinnedWindow(activeHwnd)`
`If (isPinned = 1)` ====> you need 2 "=" not one(i guess), so: ===>`If (isPinned == 1)`

do not put functions inside `msgbox`, sadly is not like python or others
`msgBox, Unpined PinWindow(activeHwnd)`
do this:
```autohotkey
var := PinWindow(activeHwnd)
msgBox, Unpined %var%
```
also `PinWindow()` funtion does not return any variables, so `var` is going to be empty, maybe you want to use `IsWindowPinned(activeHwnd)`?

also don't use `else if` unless is necessary, use `else` only in this case, it's easier to read to others and for your future self

also don´t forget to return at the end of your code

And next time put your code in a code block so I can see it, and not all in one line(search for te icon that has <>)

**Comment by itzjakm** [comment]
It works, thank you.
